# Generated by Django 3.2.19 on 2023-10-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permisoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeunico', models.TextField(max_length=20)),
                ('numeros', models.IntegerField()),
            ],
        ),
    ]
