# Generated by Django 3.2.19 on 2023-10-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permisoes',
        ),
    ]
