# Generated by Django 3.2.19 on 2023-10-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_permisoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisoes',
            old_name='pisx',
            new_name='chavep',
        ),
    ]
