# Generated by Django 3.2.19 on 2023-10-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231020_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permisoes',
        ),
    ]
