# Generated by Django 3.2.19 on 2023-10-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_datanumero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datanumero',
        ),
    ]
