# Generated by Django 3.2.19 on 2023-10-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_datanumero'),
    ]

    operations = [
        migrations.CreateModel(
            name='naorepeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebenumero', models.TextField(max_length=20)),
            ],
        ),
    ]
