# Generated by Django 3.2.19 on 2023-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_descri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descri',
            name='escrevadescricao',
            field=models.TextField(max_length=1000),
        ),
    ]
