# Generated by Django 3.2.19 on 2023-10-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_descri_escrevadescricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descri',
            name='escrevadescricao',
            field=models.TextField(max_length=5000),
        ),
    ]
